In [1]:
from bs4 import BeautifulSoup
import requests

In [23]:
url = "http://esportlivescore.com/d_2020-05-13_g_csgo.html"
page = requests.get(url)
soup = BeautifulSoup(page.text)

In [24]:
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <meta charset="utf-8"/>
  <meta content="10XY3aK7ddShRFvtg8grmb5EX3D4KdK4MfCwm9w8" name="csrf-token"/>
  <script src="/build/js/all-51f85f0ef1.js" type="text/javascript">
  </script>
  <script src="/build/js/app-9544ca3f27.js" type="text/javascript">
  </script>
  <link href="/build/css/all-a1da557634.css" rel="stylesheet" type="text/css"/>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.0.2/css/swiper.min.css" rel="stylesheet"/>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.0.2/js/swiper.min.js">
  </script>
  <script src="/build/js/gg-17aafc8963.js" type="text/javascript">
  </script>
  <title>
   2020-05-13 - CS GO - livescore, live results, matches, scores, streams
  </title>
  <meta content="2020-05-13 - CS GO - CSGO - eSportLiveScore.com is the best place to check schedule, match results and live scores of your favourite game" name="des

In [25]:
home_team_dump = soup.find_all("div", class_="team-home")

In [26]:
home_team_dump[0].div.a.img["title"]

'Espada'

In [27]:
import numpy as np

In [72]:
def get_home_teams(soup):
    home_team_dump = soup.find_all("div", class_="team-home")
    home_vec = np.empty((0,0))
    for i in range(len(home_team_dump)):
        try:
            home_vec = np.append(home_vec, home_team_dump[i].div.a.img["title"])
        except:
            pass
    print(home_vec, len(home_vec))
    return home_vec

['Endpoint' 'Nemiga' 'FATE' 'AGF' 'Singularity' 'Ambush' 'Bantz' 'FATE'
 'LDLC' 'W7M' 'Secret' 'NiP' 'Astralis' 'Sprout' 'KINGZZZ'] 15


In [28]:
def get_away_teams(soup):
    away_team_dump = soup.find_all("div", class_="team-away")
    away_vec = np.empty((0,0))
    for i in range(len(away_team_dump)):
        try:
            away_vec = np.append(away_vec, away_team_dump[i].div.a.img["title"])
        except:
            pass
    print(away_vec, len(away_vec)) 
    return away_vec

In [29]:
get_away_teams(soup)

['compLexity' 'Movistar Riders' 'NiP' 'Skyfire' 'Sinners' 'FURY' 'Nemiga'
 'Sinners' 'PC419' 'Forbidden' 'Secret' 'Infinity' 'Recon 5' 'Mythic'
 'Rugratz' 'blood, sweat, and tears' 'AA' 'Nordavind' 'Giants' 'AGO'] 20


array(['compLexity', 'Movistar Riders', 'NiP', 'Skyfire', 'Sinners',
       'FURY', 'Nemiga', 'Sinners', 'PC419', 'Forbidden', 'Secret',
       'Infinity', 'Recon 5', 'Mythic', 'Rugratz',
       'blood, sweat, and tears', 'AA', 'Nordavind', 'Giants', 'AGO'],
      dtype='<U32')

In [82]:
soup.find_all("span", class_="home-runningscore")[2].text

'1'

In [84]:
def get_home_scores(soup):
    home_score_dump = soup.find_all("span", class_="home-runningscore")
    home_score_vec = np.empty((0,0))
    for i in range(len(home_score_dump)):
        try:
            home_score_vec = np.append(home_score_vec, int(home_score_dump[i].text))
        except:
            pass
    print(home_score_vec, len(home_score_vec))
    return home_score_vec

In [86]:
get_home_scores(soup)

[2. 0. 1. 0. 1. 2. 0. 2. 1. 2. 0. 2. 3. 0. 2.] 15


array([2., 0., 1., 0., 1., 2., 0., 2., 1., 2., 0., 2., 3., 0., 2.])

In [87]:
def get_away_scores(soup):
    away_score_dump = soup.find_all("span", class_="away-runningscore")
    away_score_vec = np.empty((0,0))
    for i in range(len(away_score_dump)):
        try:
            away_score_vec = np.append(away_score_vec, int(away_score_dump[i].text))
        except:
            pass
    print(away_score_vec, len(away_score_vec))
    return away_score_vec

In [88]:
get_away_scores(soup)

[0. 1. 2. 2. 2. 0. 1. 1. 2. 0. 2. 1. 0. 2. 0.] 15


array([0., 1., 2., 2., 2., 0., 1., 1., 2., 0., 2., 1., 0., 2., 0.])